-- 1. Create database
CREATE DATABASE IF NOT EXISTS ewaste_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE ewaste_db;

-- 2. Users table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  address TEXT,
  role ENUM('user','collector','admin') NOT NULL DEFAULT 'user',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 3. E-waste items (items user wants to dispose)
CREATE TABLE ewaste_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  item_type VARCHAR(100) NOT NULL,      -- e.g. "Mobile", "Laptop", "PCB", "Battery"
  brand VARCHAR(100),
  model VARCHAR(100),
  condition ENUM('working','partly_working','not_working') DEFAULT 'not_working',
  quantity INT NOT NULL DEFAULT 1,
  description TEXT,
  image_path VARCHAR(255),
  status ENUM('pending','scheduled','collected','recycled','disposed') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 4. Pickups (a pickup request)
CREATE TABLE pickups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  pickup_date DATE,                      -- requested or scheduled date
  pickup_time TIME,
  pickup_address TEXT,
  assigned_collector_id INT NULL,        -- user id of collector role
  status ENUM('requested','scheduled','in_transit','completed','cancelled') DEFAULT 'requested',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_collector_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 5. Pickup ↔ Items linking (a pickup can include multiple items)
CREATE TABLE pickup_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pickup_id INT NOT NULL,
  ewaste_item_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pickup_id) REFERENCES pickups(id) ON DELETE CASCADE,
  FOREIGN KEY (ewaste_item_id) REFERENCES ewaste_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 6. Tracking / history for pickups
CREATE TABLE pickup_tracking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pickup_id INT NOT NULL,
  status ENUM('requested','collector_assigned','picked_up','in_transit','arrived_at_center','completed','cancelled') NOT NULL,
  location VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pickup_id) REFERENCES pickups(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 7. Optional: recycling_centers (if you route to centers)
CREATE TABLE recycling_centers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  address TEXT,
  contact_phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 8. Indexes for common queries
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_items_user ON ewaste_items(user_id);
CREATE INDEX idx_pickups_user ON pickups(user_id);
CREATE INDEX idx_tracking_pickup ON pickup_tracking(pickup_id);

-- 9. Sample admin user (password: ChangeMe123)
INSERT INTO users (name, email, password_hash, phone, role)
VALUES ('Admin', 'admin@example.com', 
        -- replace with actual hash generated by PHP's password_hash; this is placeholder:
        '$2y$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        '9999999999', 'admin');
